### ISSUE TITLE
Is there a colormap in  matplotlib the same as this repo

### ISSUE THREAD

**Issue by Ryuk17** [dofuuz/audacity-colormap#1]
Hi dofuuz, I like this colormap, so I wonder if I can find the same colormap as this picture in [matplotlib](https://matplotlib.org/2.0.2/examples/color/colormaps_reference.html) ? ![image](https://user-images.githubusercontent.com/22525811/157241867-3f1cf87d-5248-4730-8455-730ec909cdc6.png)

**Comment by dofuuz** [comment]
Use custom colormap for matplotlib.
https://gist.github.com/dofuuz/282036bd1c58be1c707bf39a1a3371d7#file-plot-py

**Comment by Ryuk17** [comment]
That's coooooooooool, thank you!
